

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./storage:/storage:ro
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: yarik
      DB_DATABASE: rawcrownz
    volumes:
      - ./storage:/app/storage:rw
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: yarik
      POSTGRES_DB: rawcrownz
    networks:
      - app-network

volumes:
  postgres-data:
  
networks:
  app-network:
    driver: bridge